# Generated by Django 6.0.6 on 2026-07-02 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_library', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaasset',
            name='kind',
            field=models.CharField(blank=True, choices=[('image', 'Image'), ('video', 'Video'), ('file', 'File')], default='', max_length=10),
        ),
    ]
